### ISSUE TITLE
Project missing license file 

### ISSUE THREAD

**Issue by kshithijiyer** [intel/rsp-sw-toolkit-im-suite-inventory-suite#1]

**Comment by saites** [comment]
The individual Go submodules each have an Apache 2.0 License doc, and most of the files (including those in this repo) include a short statement about being Apache 2.0 licensed; but to prevent confusion, we should probably include an overarching license doc in this repo as well. It also looks like the demo-ui submodule only uses headers, rather than adding a document.

Thank you for pointing it out.

**Comment by ajcasagrande** [comment]
License added. As @saites said, it is Apache 2.0
